### ISSUE TITLE
Using subplot and other matplotlib functionality

### ISSUE THREAD

**Issue by Mathadon** [kdavies4/ModelicaRes#31]
Hi,

I started working with ModelicaRes today. I was exploring the options but I'm stuck at the following. 

I'd like to use the subplot command from matplotlib. Intuitively I tried:
```
sim = SimRes(arguments)
sim.add_subplot(2,1,1)    //from http://matplotlib.org/examples/animation/subplots.html
sim.plot(title="Title", ynames1=  ... etc)
```
but this does not seem to work. I can't seem to find an example in the documentation either. How can I approach this?

Thank you!

**Comment by kdavies4** [comment]
Filip, I got swamped and missed this. I'm sorry for the delay. Try something like this:

```
from modelicares import SimRes
from matplotlib import pyplot as plt

sim = SimRes('ChuaCircuit.mat')
ax = plt.subplot(121)
sim.plot('L.v', ax1=ax)
ax = plt.subplot(122)
sim.plot('L.i', ax1=ax)
plt.show()
```

The relevant documentation is [here](http://kdavies4.github.io/ModelicaRes/modelicares.simres.html#modelicares.simres.SimRes.plot), although I admit that solution isn't obvious.

**Comment by kdavies4** [comment]
If that works for you, feel free to close this issue.

**Comment by Mathadon** [comment]
thanks @kdavies4 
I'm sure it works but I started using 'regular' matPlotLib plots in the meantime :)
